# hooks/post_gen_project.py (trecho final)
LANG = "{{ cookiecutter.ui_language }}".lower()

if LANG == "pt":
    print("\n✅ Projeto criado com sucesso!")
    print("ℹ️  Próximos passos:")
    print("   - Conecte ao GitHub:")
    print("       git remote add origin <URL>")
    print("       git branch -M main")
    print("       git push -u origin main")
    print("   - Ambiente conda:")
    print("       conda env create -f env/environment.yml")
    print("       conda activate lcp")
else:
    print("\n✅ Project created successfully!")
    print("ℹ️  Next steps:")
    print("   - Connect to GitHub:")
    print("       git remote add origin <URL>")
    print("       git branch -M main")
    print("       git push -u origin main")
    print("   - Conda environment:")
    print("       conda env create -f env/environment.yml")
    print("       conda activate lcp")
